name: ont_datafetch
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.9.0
  - appdirs=1.4.4
  - asttokens=3.0.0
  - attrs=25.3.0
  - beautifulsoup4=4.13.3
  - bio=1.8.0
  - biopython=1.85
  - biothings_client=0.4.1
  - brotli-python=1.1.0
  - bs4=4.13.3
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cachetools=6.1.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.13
  - decorator=5.2.1
  - entrez-direct=24.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - frozendict=2.4.6
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gprofiler-official=1.0.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20250104
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libiconv=1.18
  - libidn2=2.3.7
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libopenblas=0.3.28
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libxml2=2.13.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lxml=5.4.0
  - matplotlib-inline=0.1.7
  - mygene=3.2.2
  - narwhals=1.32.0
  - nbformat=5.10.4
  - ncbi-genome-download=0.3.3
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.2.3
  - openssl=3.5.2
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - plotly=6.0.1
  - pooch=1.8.2
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyld=2.0.4
  - pysocks=1.7.1
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-tzdata=2025.1
  - python_abi=3.13
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.3.0
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rpds-py=0.24.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - taxonkit=0.18.0
  - tk=8.6.13
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wget=1.21.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
